version: '3.4'

services:
  crud:
    image: crud
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    networks: 
      - multi-tier-docker
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

networks:
  multi-tier-docker:
    driver: bridge

volumes:
  mongodb:
  mongodb_config: